#!/bin/sh

# Use nvim for vim
alias vim="nvim" vimdiff="nvim -d"

# Useful file management
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mf="touch" \
	md="mkdir -pv"

# Colorized commands
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto"

# Shorten commands
alias \
	ka="killall" \
	g="git" \
	f="$FILE" \
	v="$EDITOR" \
	t="tmux-attach" \
	open="xdg-open" \

# Dotfiles
alias \
    d="/usr/bin/git --git-dir=$XDG_DATA_HOME/.dotfiles/ --work-tree=$HOME"
