#!/bin/sh

while read file
do
    case "$1" in
    "w") setbg "$file" & ;;
    "r") convert -rotate 90 "$file" "$file" ;;
    "R") convert -rotate -90 "$file" "$file" ;;
    "f") convert -flop "$file" "$file" ;;
    "y") echo -n "$file" | xclip -i -sel clip && notify-send "$file copied to clipboard" & ;;
    "Y") readlink -f "$file" | xclip -i -sel clip && notify-send "$(readlink -f "$file") copied to clipboard" & ;;
    "d") rm "$file" && notify-send "$file deleted." ;;
    "g") gimp "$file" & ;;
    esac
done

