autorandr -c &                                                                                  # Setup monitors
xrdb -merge ~/.config/X11/Xresources &                                                          # Set colors/fonts
udiskie &                                                                                       # Mounting Daemon
remaps &                                                                                        # Remap keys (caps,ctrl,lock)
libinput-gestures -c ~/.config/libinput/awesome.conf &                                          # Enable trackpad gestures
transmission-daemon &                                                                           # Torrent Daemon
xss-lock -l -- betterlockscreen -l &                                                            # Set lock hook
picom -b &                                                                                      # Transparency Daemon
