/usr/bin/prime-offload                                                                          # Enable GPU Switching
xrdb -merge ~/.config/X11/Xresources                                                            # Set colors/fonts
flux &                                                                                          # Screen temperature daemon
sxhkd &                                                                                         # Hotkey Daemon
udiskie &                                                                                       # Mounting Daemon
dunst &                                                                                         # Notification Daemon
remaps &                                                                                        # Remap keys (caps,ctrl,lock)
libinput-gestures -c ~/.config/libinput/libinput-gestures.conf &                                # Enable trackpad gestures
transmission-daemon &                                                                           # Torrent Daemon
xsetroot -xcf /usr/share/icons/Adwaita/cursors/left_ptr 16 &                                    # Set normal cursor
xss-lock -n /home/infinity/.local/bin/utils/dim-screen -l -- betterlockscreen -l &              # Set lock hook
picom --experimental-backends -b &                                                              # Transparency Daemon
srandrd bspxrandr &                                                                             # Monitor Daemon
exec bspwm                                                                                      # Window Manager
