#!/bin/sh
bspc rule -r "*"

## Autostart

bspxrandr initialize                        # Monitors, bar and set wallpaper
(pidof -x bspswallow) || bspswallow &       # Swallowing
(pgrep bspdragtab) || bspdragtab &          # Chromium tabs float when dragged

## Settings

# Monitor Settings
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Scheme Settings
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config borderless_monocle true
bspc config gapless_monocle true

# Pointer Settings
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none
bspc config focus_follows_pointer true

# Border Colors
bspc config normal_border_color "#121212"
bspc config active_border_color "#121212"
bspc config focused_border_color "#FF8700"

# Window Settings
bspc config top_padding 32
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 1
bspc config window_gap 10

bspc config external_rules_command "$(which external_rules)"

# General Rules
bspc rule -a Zathura state=tiled
bspc rule -a discord desktop='^2'
bspc rule -a spotify desktop='^2'
bspc rule -a st-256color:scratch sticky=on state=floating rectangle=800x600+10+10
bspc rule -a '*:*:Picture in picture' state=floating

# Matlab fix rules
bspc rule -a 'MATLAB R2020b - academic use:sun-awt-X11-XWindowPeer:DefaultOverlayManager.JWindow' manage=off
bspc rule -a 'MATLAB R2020b - academic use:sun-awt-X11-XWindowPeer:TabCompletionPopup' manage=off
bspc rule -a 'MATLAB R2020b - academic use:sun-awt-X11-XWindowPeer:FunctionHints' manage=off
bspc rule -a 'MATLAB R2020b - academic use:sun-awt-X11-XWindowPeer:Command HistoryWindow' manage=off
bspc rule -a 'MATLAB R2020b - academic use:sun-awt-X11-XDialogPeer' center=off focus=off
