[bell]
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[font]
builtin_box_drawing = true
size = 7.0

[font.normal]
family = "Roboto Mono Nerd Font"
style = "Regular"

[window.padding]
x = 5
y = 5
